import unittest
import importlib
import python_ics
from types import ModuleType


class TestModStructures(unittest.TestCase):
    @classmethod
    def setUpClass(self):
        pass

    @classmethod
    def setUp(self):
        pass

    @classmethod
    def tearDownClass(self):
        pass

    def test_version(self):
        self.assertTrue(hasattr(python_ics, "__version__"))
        self.assertTrue(hasattr(python_ics, "__full_version__"))
        self.assertTrue(hasattr(python_ics, "BUILD_DATETIME"))

    def test_hidden_imports(self):
        self.assertIs(type(importlib.import_module('python_ics.hiddenimports', python_ics)), ModuleType)

    def test_PyNeoDeviceEx(self):
        py_neo_device_ex = importlib.import_module('python_ics.py_neo_device_ex', python_ics)
        self.assertIs(type(py_neo_device_ex), ModuleType)

        self.assertTrue(hasattr(py_neo_device_ex, "PyNeoDeviceEx"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "_handle"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "_name"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "_auto_handle_close"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "_Handle"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "Name"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "DeviceType"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "Handle"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "NumberOfClients"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "MaxAllowedClients"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "SerialNumber"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "serial_number"))

        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "close"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_clear"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_get_fblock_status"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_get_status"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_load"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_read_app_signal"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_read_rx_message"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_read_tx_message"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_start"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_start_fblock"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_stop"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_stop_fblock"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_write_app_signal"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_write_rx_message"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "coremini_write_tx_message"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "create_neovi_radio_message"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "disk_format"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "disk_format_cancel"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "enable_bus_voltage_monitor"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "enable_doip_line"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "enable_network_com"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "firmware_update_required"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "flash_accessory_firmware"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "force_firmware_update"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "generic_api_get_status"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "generic_api_read_data"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "generic_api_send_command"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_accessory_firmware_version"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_active_vnet_channel"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_all_chip_versions"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_backup_power_enabled"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_backup_power_ready"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_bus_voltage"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_device_settings"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_device_status"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_disk_details"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_disk_format_progress"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_dll_firmware_info"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_error_messages"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_gptp_status"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_hw_firmware_info"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_last_api_error"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_messages"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_pcb_serial_number"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_performance_parameters"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_rtc"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_script_status"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_serial_number"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "get_timestamp_for_msg"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "is_device_feature_supported"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "iso15765_disable_networks"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "iso15765_enable_networks"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "iso15765_receive_message"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "iso15765_transmit_message"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "load_default_settings"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "open"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "read_jupiter_firmware"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "read_sdcard"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "request_enter_sleep_mode"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "set_active_vnet_channel"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "set_backup_power_enabled"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "set_bit_rate"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "set_bit_rate_ex"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "set_device_settings"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "set_fd_bit_rate"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "set_led_property"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "set_rtc"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "set_safe_boot_mode"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "start_dhcp_server"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "stop_dhcp_server"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "transmit_messages"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "uart_get_baudrate"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "uart_read"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "uart_set_baudrate"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "uart_write"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "validate_hobject"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "wbms_manager_reset"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "wbms_manager_write_lock"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "write_jupiter_firmware"))
        self.assertTrue(hasattr(py_neo_device_ex.PyNeoDeviceEx, "write_sdcard"))

    def test_cmod_imports(self):
        self.assertIs(type(importlib.import_module('python_ics.c_mod', python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module('python_ics.c_mod', python_ics)), ModuleType)

        c_mod = importlib.import_module('python_ics.c_mod', python_ics)
        self.assertTrue(callable(c_mod.find_devices))

        self.assertTrue(callable(c_mod.ClosePort))
        self.assertTrue(callable(c_mod.EnableBusVoltageMonitor))
        self.assertTrue(callable(c_mod.EnableDOIPLine))
        self.assertTrue(callable(c_mod.EnableNetworkCom))
        self.assertTrue(callable(c_mod.FindNeoDevices))
        self.assertTrue(callable(c_mod.FirmwareUpdateRequired))
        self.assertTrue(callable(c_mod.FlashAccessoryFirmware))
        self.assertTrue(callable(c_mod.ForceFirmwareUpdate))
        self.assertTrue(callable(c_mod.GenericAPIGetStatus))
        self.assertTrue(callable(c_mod.GenericAPIReadData))
        self.assertTrue(callable(c_mod.GenericAPISendCommand))
        self.assertTrue(callable(c_mod.GetAccessoryFwVersion))
        self.assertTrue(callable(c_mod.GetActiveVNETChannel))
        self.assertTrue(callable(c_mod.GetAllChipVersions))
        self.assertTrue(callable(c_mod.GetBackupPowerEnabled))
        self.assertTrue(callable(c_mod.GetBackupPowerReady))
        self.assertTrue(callable(c_mod.GetBusVoltage))
        self.assertTrue(callable(c_mod.GetDLLFirmwareInfo))
        self.assertTrue(callable(c_mod.GetDLLVersion))
        self.assertTrue(callable(c_mod.GetDeviceSettings))
        self.assertTrue(callable(c_mod.GetDeviceStatus))
        self.assertTrue(callable(c_mod.GetErrorMessages))
        self.assertTrue(callable(c_mod.GetGPTPStatus))
        self.assertTrue(callable(c_mod.GetHWFirmwareInfo))
        self.assertTrue(callable(c_mod.GetLastAPIError))
        self.assertTrue(callable(c_mod.GetMessages))
        self.assertTrue(callable(c_mod.GetPCBSerialNumber))
        self.assertTrue(callable(c_mod.GetPerformanceParameters))
        self.assertTrue(callable(c_mod.GetRTC))
        self.assertTrue(callable(c_mod.GetSerialNumber))
        self.assertTrue(callable(c_mod.GetTimeStampForMsg))
        self.assertTrue(callable(c_mod.ISO15765_DisableNetworks))
        self.assertTrue(callable(c_mod.ISO15765_EnableNetworks))
        self.assertTrue(callable(c_mod.ISO15765_ReceiveMessage))
        self.assertTrue(callable(c_mod.ISO15765_TransmitMessage))
        self.assertTrue(callable(c_mod.IsDeviceFeatureSupported))
        self.assertTrue(callable(c_mod.LoadDefaultSettings))
        self.assertTrue(callable(c_mod.OpenNeoDevice))
        self.assertTrue(callable(c_mod.ReadJupiterFirmware))
        self.assertTrue(callable(c_mod.ReadSDCard))
        self.assertTrue(callable(c_mod.RequestDiskDetails))
        self.assertTrue(callable(c_mod.RequestDiskFormat))
        self.assertTrue(callable(c_mod.RequestDiskFormatCancel))
        self.assertTrue(callable(c_mod.RequestDiskFormatProgress))
        self.assertTrue(callable(c_mod.RequestEnterSleepMode))
        self.assertTrue(callable(c_mod.RuntimeError))
        self.assertTrue(callable(c_mod.ScriptClear))
        self.assertTrue(callable(c_mod.ScriptGetFBlockStatus))
        self.assertTrue(callable(c_mod.ScriptGetScriptStatus))
        self.assertTrue(callable(c_mod.ScriptGetScriptStatusEx))
        self.assertTrue(callable(c_mod.ScriptLoad))
        self.assertTrue(callable(c_mod.ScriptReadAppSignal))
        self.assertTrue(callable(c_mod.ScriptReadRxMessage))
        self.assertTrue(callable(c_mod.ScriptReadTxMessage))
        self.assertTrue(callable(c_mod.ScriptStart))
        self.assertTrue(callable(c_mod.ScriptStartFBlock))
        self.assertTrue(callable(c_mod.ScriptStop))
        self.assertTrue(callable(c_mod.ScriptStopFBlock))
        self.assertTrue(callable(c_mod.ScriptWriteAppSignal))
        self.assertTrue(callable(c_mod.ScriptWriteRxMessage))
        self.assertTrue(callable(c_mod.ScriptWriteTxMessage))
        self.assertTrue(callable(c_mod.SetActiveVNETChannel))
        self.assertTrue(callable(c_mod.SetBackupPowerEnabled))
        self.assertTrue(callable(c_mod.SetBitRate))
        self.assertTrue(callable(c_mod.SetBitRateEx))
        self.assertTrue(callable(c_mod.SetContext))
        self.assertTrue(callable(c_mod.SetDeviceSettings))
        self.assertTrue(callable(c_mod.SetFDBitRate))
        self.assertTrue(callable(c_mod.SetLedProperty))
        self.assertTrue(callable(c_mod.SetRTC))
        self.assertTrue(callable(c_mod.SetReflashDisplayCallback))
        self.assertTrue(callable(c_mod.SetSafeBootMode))
        self.assertTrue(callable(c_mod.SpyMessage))
        self.assertTrue(callable(c_mod.SpyMessageJ1850))
        self.assertTrue(callable(c_mod.StartDHCPServer))
        self.assertTrue(callable(c_mod.StopDHCPServer))
        self.assertTrue(callable(c_mod.TxMessages))
        self.assertTrue(callable(c_mod.UartGetBaudrate))
        self.assertTrue(callable(c_mod.UartRead))
        self.assertTrue(callable(c_mod.UartSetBaudrate))
        self.assertTrue(callable(c_mod.UartWrite))
        self.assertTrue(callable(c_mod.ValidateHObject))
        self.assertTrue(callable(c_mod.WriteJupiterFirmware))
        self.assertTrue(callable(c_mod.WriteSDCard))
        self.assertTrue(callable(c_mod.base36enc))
        self.assertTrue(callable(c_mod.close_device))
        self.assertTrue(callable(c_mod.coremini_clear))
        self.assertTrue(callable(c_mod.coremini_get_fblock_status))
        self.assertTrue(callable(c_mod.coremini_get_status))
        self.assertTrue(callable(c_mod.coremini_load))
        self.assertTrue(callable(c_mod.coremini_read_app_signal))
        self.assertTrue(callable(c_mod.coremini_read_rx_message))
        self.assertTrue(callable(c_mod.coremini_read_tx_message))
        self.assertTrue(callable(c_mod.coremini_start))
        self.assertTrue(callable(c_mod.coremini_start_fblock))
        self.assertTrue(callable(c_mod.coremini_stop))
        self.assertTrue(callable(c_mod.coremini_stop_fblock))
        self.assertTrue(callable(c_mod.coremini_write_app_signal))
        self.assertTrue(callable(c_mod.coremini_write_rx_message))
        self.assertTrue(callable(c_mod.coremini_write_tx_message))
        self.assertTrue(callable(c_mod.create_neovi_radio_message))
        self.assertTrue(callable(c_mod.disk_format))
        self.assertTrue(callable(c_mod.disk_format_cancel))
        self.assertTrue(callable(c_mod.enable_bus_voltage_monitor))
        self.assertTrue(callable(c_mod.enable_doip_line))
        self.assertTrue(callable(c_mod.enable_network_com))
        self.assertTrue(callable(c_mod.find_devices))
        self.assertTrue(callable(c_mod.firmware_update_required))
        self.assertTrue(callable(c_mod.flash_accessory_firmware))
        self.assertTrue(callable(c_mod.force_firmware_update))
        self.assertTrue(callable(c_mod.generic_api_get_status))
        self.assertTrue(callable(c_mod.generic_api_read_data))
        self.assertTrue(callable(c_mod.generic_api_send_command))
        self.assertTrue(callable(c_mod.get_accessory_firmware_version))
        self.assertTrue(callable(c_mod.get_active_vnet_channel))
        self.assertTrue(callable(c_mod.get_all_chip_versions))
        self.assertTrue(callable(c_mod.get_backup_power_enabled))
        self.assertTrue(callable(c_mod.get_backup_power_ready))
        self.assertTrue(callable(c_mod.get_bus_voltage))
        self.assertTrue(callable(c_mod.get_device_settings))
        self.assertTrue(callable(c_mod.get_device_status))
        self.assertTrue(callable(c_mod.get_disk_details))
        self.assertTrue(callable(c_mod.get_disk_format_progress))
        self.assertTrue(callable(c_mod.get_dll_firmware_info))
        self.assertTrue(callable(c_mod.get_dll_version))
        self.assertTrue(callable(c_mod.get_error_messages))
        self.assertTrue(callable(c_mod.get_gptp_status))
        self.assertTrue(callable(c_mod.get_hw_firmware_info))
        self.assertTrue(callable(c_mod.get_last_api_error))
        self.assertTrue(callable(c_mod.get_library_path))
        self.assertTrue(callable(c_mod.get_messages))
        self.assertTrue(callable(c_mod.get_pcb_serial_number))
        self.assertTrue(callable(c_mod.get_performance_parameters))
        self.assertTrue(callable(c_mod.get_rtc))
        self.assertTrue(callable(c_mod.get_script_status))
        self.assertTrue(callable(c_mod.get_serial_number))
        self.assertTrue(callable(c_mod.get_timestamp_for_msg))
        self.assertTrue(callable(c_mod.icsneoClosePort))
        self.assertTrue(callable(c_mod.icsneoEnableBusVoltageMonitor))
        self.assertTrue(callable(c_mod.icsneoEnableDOIPLine))
        self.assertTrue(callable(c_mod.icsneoEnableNetworkCom))
        self.assertTrue(callable(c_mod.icsneoFindNeoDevices))
        self.assertTrue(callable(c_mod.icsneoFirmwareUpdateRequired))
        self.assertTrue(callable(c_mod.icsneoFlashAccessoryFirmware))
        self.assertTrue(callable(c_mod.icsneoForceFirmwareUpdate))
        self.assertTrue(callable(c_mod.icsneoGenericAPIGetStatus))
        self.assertTrue(callable(c_mod.icsneoGenericAPIReadData))
        self.assertTrue(callable(c_mod.icsneoGenericAPISendCommand))
        self.assertTrue(callable(c_mod.icsneoGetAccessoryFwVersion))
        self.assertTrue(callable(c_mod.icsneoGetActiveVNETChannel))
        self.assertTrue(callable(c_mod.icsneoGetAllChipVersions))
        self.assertTrue(callable(c_mod.icsneoGetBackupPowerEnabled))
        self.assertTrue(callable(c_mod.icsneoGetBackupPowerReady))
        self.assertTrue(callable(c_mod.icsneoGetBusVoltage))
        self.assertTrue(callable(c_mod.icsneoGetDLLFirmwareInfo))
        self.assertTrue(callable(c_mod.icsneoGetDLLVersion))
        self.assertTrue(callable(c_mod.icsneoGetDeviceSettings))
        self.assertTrue(callable(c_mod.icsneoGetDeviceStatus))
        self.assertTrue(callable(c_mod.icsneoGetErrorMessages))
        self.assertTrue(callable(c_mod.icsneoGetGPTPStatus))
        self.assertTrue(callable(c_mod.icsneoGetHWFirmwareInfo))
        self.assertTrue(callable(c_mod.icsneoGetLastAPIError))
        self.assertTrue(callable(c_mod.icsneoGetMessages))
        self.assertTrue(callable(c_mod.icsneoGetPCBSerialNumber))
        self.assertTrue(callable(c_mod.icsneoGetPerformanceParameters))
        self.assertTrue(callable(c_mod.icsneoGetRTC))
        self.assertTrue(callable(c_mod.icsneoGetSerialNumber))
        self.assertTrue(callable(c_mod.icsneoGetTimeStampForMsg))
        self.assertTrue(callable(c_mod.icsneoISO15765_DisableNetworks))
        self.assertTrue(callable(c_mod.icsneoISO15765_EnableNetworks))
        self.assertTrue(callable(c_mod.icsneoISO15765_ReceiveMessage))
        self.assertTrue(callable(c_mod.icsneoISO15765_TransmitMessage))
        self.assertTrue(callable(c_mod.icsneoIsDeviceFeatureSupported))
        self.assertTrue(callable(c_mod.icsneoLoadDefaultSettings))
        self.assertTrue(callable(c_mod.icsneoOpenNeoDevice))
        self.assertTrue(callable(c_mod.icsneoReadJupiterFirmware))
        self.assertTrue(callable(c_mod.icsneoReadSDCard))
        self.assertTrue(callable(c_mod.icsneoRequestDiskDetails))
        self.assertTrue(callable(c_mod.icsneoRequestDiskFormat))
        self.assertTrue(callable(c_mod.icsneoRequestDiskFormatCancel))
        self.assertTrue(callable(c_mod.icsneoRequestDiskFormatProgress))
        self.assertTrue(callable(c_mod.icsneoRequestEnterSleepMode))
        self.assertTrue(callable(c_mod.icsneoScriptClear))
        self.assertTrue(callable(c_mod.icsneoScriptGetFBlockStatus))
        self.assertTrue(callable(c_mod.icsneoScriptGetScriptStatus))
        self.assertTrue(callable(c_mod.icsneoScriptGetScriptStatusEx))
        self.assertTrue(callable(c_mod.icsneoScriptLoad))
        self.assertTrue(callable(c_mod.icsneoScriptReadAppSignal))
        self.assertTrue(callable(c_mod.icsneoScriptReadRxMessage))
        self.assertTrue(callable(c_mod.icsneoScriptReadTxMessage))
        self.assertTrue(callable(c_mod.icsneoScriptStart))
        self.assertTrue(callable(c_mod.icsneoScriptStartFBlock))
        self.assertTrue(callable(c_mod.icsneoScriptStop))
        self.assertTrue(callable(c_mod.icsneoScriptStopFBlock))
        self.assertTrue(callable(c_mod.icsneoScriptWriteAppSignal))
        self.assertTrue(callable(c_mod.icsneoScriptWriteRxMessage))
        self.assertTrue(callable(c_mod.icsneoScriptWriteTxMessage))
        self.assertTrue(callable(c_mod.icsneoSetActiveVNETChannel))
        self.assertTrue(callable(c_mod.icsneoSetBackupPowerEnabled))
        self.assertTrue(callable(c_mod.icsneoSetBitRate))
        self.assertTrue(callable(c_mod.icsneoSetBitRateEx))
        self.assertTrue(callable(c_mod.icsneoSetContext))
        self.assertTrue(callable(c_mod.icsneoSetDeviceSettings))
        self.assertTrue(callable(c_mod.icsneoSetFDBitRate))
        self.assertTrue(callable(c_mod.icsneoSetLedProperty))
        self.assertTrue(callable(c_mod.icsneoSetRTC))
        self.assertTrue(callable(c_mod.icsneoSetReflashDisplayCallbacks))
        self.assertTrue(callable(c_mod.icsneoSetSafeBootMode))
        self.assertTrue(callable(c_mod.icsneoStartDHCPServer))
        self.assertTrue(callable(c_mod.icsneoStopDHCPServer))
        self.assertTrue(callable(c_mod.icsneoTxMessages))
        self.assertTrue(callable(c_mod.icsneoUartGetBaudrate))
        self.assertTrue(callable(c_mod.icsneoUartRead))
        self.assertTrue(callable(c_mod.icsneoUartSetBaudrate))
        self.assertTrue(callable(c_mod.icsneoUartWrite))
        self.assertTrue(callable(c_mod.icsneoValidateHObject))
        self.assertTrue(callable(c_mod.icsneoWriteJupiterFirmware))
        self.assertTrue(callable(c_mod.icsneoWriteSDCard))
        self.assertTrue(callable(c_mod.icsneowBMSManagerReset))
        self.assertTrue(callable(c_mod.icsneowBMSManagerWriteLock))
        self.assertTrue(callable(c_mod.is_device_feature_supported))
        self.assertTrue(callable(c_mod.iso15765_disable_networks))
        self.assertTrue(callable(c_mod.iso15765_enable_networks))
        self.assertTrue(callable(c_mod.iso15765_receive_message))
        self.assertTrue(callable(c_mod.iso15765_transmit_message))
        self.assertTrue(callable(c_mod.load_default_settings))
        self.assertTrue(callable(c_mod.open_device))
        self.assertTrue(callable(c_mod.override_library_name))
        self.assertTrue(callable(c_mod.read_jupiter_firmware))
        self.assertTrue(callable(c_mod.read_sdcard))
        self.assertTrue(callable(c_mod.request_enter_sleep_mode))
        self.assertTrue(callable(c_mod.set_active_vnet_channel))
        self.assertTrue(callable(c_mod.set_backup_power_enabled))
        self.assertTrue(callable(c_mod.set_bit_rate))
        self.assertTrue(callable(c_mod.set_bit_rate_ex))
        self.assertTrue(callable(c_mod.set_context))
        self.assertTrue(callable(c_mod.set_device_settings))
        self.assertTrue(callable(c_mod.set_fd_bit_rate))
        self.assertTrue(callable(c_mod.set_led_property))
        self.assertTrue(callable(c_mod.set_reflash_callback))
        self.assertTrue(callable(c_mod.set_rtc))
        self.assertTrue(callable(c_mod.set_safe_boot_mode))
        self.assertTrue(callable(c_mod.start_dhcp_server))
        self.assertTrue(callable(c_mod.stop_dhcp_server))
        self.assertTrue(callable(c_mod.transmit_messages))
        self.assertTrue(callable(c_mod.uart_get_baudrate))
        self.assertTrue(callable(c_mod.uart_read))
        self.assertTrue(callable(c_mod.uart_set_baudrate))
        self.assertTrue(callable(c_mod.uart_write))
        self.assertTrue(callable(c_mod.validate_hobject))
        self.assertTrue(callable(c_mod.wBMSManagerReset))
        self.assertTrue(callable(c_mod.wBMSManagerWriteLock))
        self.assertTrue(callable(c_mod.wbms_manager_reset))
        self.assertTrue(callable(c_mod.wbms_manager_write_lock))
        self.assertTrue(callable(c_mod.write_jupiter_firmware))
        self.assertTrue(callable(c_mod.write_sdcard))

        self.assertTrue(callable(python_ics.ClosePort))
        self.assertTrue(callable(python_ics.EnableBusVoltageMonitor))
        self.assertTrue(callable(python_ics.EnableDOIPLine))
        self.assertTrue(callable(python_ics.EnableNetworkCom))
        self.assertTrue(callable(python_ics.FindNeoDevices))
        self.assertTrue(callable(python_ics.FirmwareUpdateRequired))
        self.assertTrue(callable(python_ics.FlashAccessoryFirmware))
        self.assertTrue(callable(python_ics.ForceFirmwareUpdate))
        self.assertTrue(callable(python_ics.GenericAPIGetStatus))
        self.assertTrue(callable(python_ics.GenericAPIReadData))
        self.assertTrue(callable(python_ics.GenericAPISendCommand))
        self.assertTrue(callable(python_ics.GetAccessoryFwVersion))
        self.assertTrue(callable(python_ics.GetActiveVNETChannel))
        self.assertTrue(callable(python_ics.GetAllChipVersions))
        self.assertTrue(callable(python_ics.GetBackupPowerEnabled))
        self.assertTrue(callable(python_ics.GetBackupPowerReady))
        self.assertTrue(callable(python_ics.GetBusVoltage))
        self.assertTrue(callable(python_ics.GetDLLFirmwareInfo))
        self.assertTrue(callable(python_ics.GetDLLVersion))
        self.assertTrue(callable(python_ics.GetDeviceSettings))
        self.assertTrue(callable(python_ics.GetDeviceStatus))
        self.assertTrue(callable(python_ics.GetErrorMessages))
        self.assertTrue(callable(python_ics.GetGPTPStatus))
        self.assertTrue(callable(python_ics.GetHWFirmwareInfo))
        self.assertTrue(callable(python_ics.GetLastAPIError))
        self.assertTrue(callable(python_ics.GetMessages))
        self.assertTrue(callable(python_ics.GetPCBSerialNumber))
        self.assertTrue(callable(python_ics.GetPerformanceParameters))
        self.assertTrue(callable(python_ics.GetRTC))
        self.assertTrue(callable(python_ics.GetSerialNumber))
        self.assertTrue(callable(python_ics.GetTimeStampForMsg))
        self.assertTrue(callable(python_ics.ISO15765_DisableNetworks))
        self.assertTrue(callable(python_ics.ISO15765_EnableNetworks))
        self.assertTrue(callable(python_ics.ISO15765_ReceiveMessage))
        self.assertTrue(callable(python_ics.ISO15765_TransmitMessage))
        self.assertTrue(callable(python_ics.IsDeviceFeatureSupported))
        self.assertTrue(callable(python_ics.LoadDefaultSettings))
        self.assertTrue(callable(python_ics.OpenNeoDevice))
        self.assertTrue(callable(python_ics.ReadJupiterFirmware))
        self.assertTrue(callable(python_ics.ReadSDCard))
        self.assertTrue(callable(python_ics.RequestDiskDetails))
        self.assertTrue(callable(python_ics.RequestDiskFormat))
        self.assertTrue(callable(python_ics.RequestDiskFormatCancel))
        self.assertTrue(callable(python_ics.RequestDiskFormatProgress))
        self.assertTrue(callable(python_ics.RequestEnterSleepMode))
        self.assertTrue(callable(python_ics.RuntimeError))
        self.assertTrue(callable(python_ics.ScriptClear))
        self.assertTrue(callable(python_ics.ScriptGetFBlockStatus))
        self.assertTrue(callable(python_ics.ScriptGetScriptStatus))
        self.assertTrue(callable(python_ics.ScriptGetScriptStatusEx))
        self.assertTrue(callable(python_ics.ScriptLoad))
        self.assertTrue(callable(python_ics.ScriptReadAppSignal))
        self.assertTrue(callable(python_ics.ScriptReadRxMessage))
        self.assertTrue(callable(python_ics.ScriptReadTxMessage))
        self.assertTrue(callable(python_ics.ScriptStart))
        self.assertTrue(callable(python_ics.ScriptStartFBlock))
        self.assertTrue(callable(python_ics.ScriptStop))
        self.assertTrue(callable(python_ics.ScriptStopFBlock))
        self.assertTrue(callable(python_ics.ScriptWriteAppSignal))
        self.assertTrue(callable(python_ics.ScriptWriteRxMessage))
        self.assertTrue(callable(python_ics.ScriptWriteTxMessage))
        self.assertTrue(callable(python_ics.SetActiveVNETChannel))
        self.assertTrue(callable(python_ics.SetBackupPowerEnabled))
        self.assertTrue(callable(python_ics.SetBitRate))
        self.assertTrue(callable(python_ics.SetBitRateEx))
        self.assertTrue(callable(python_ics.SetContext))
        self.assertTrue(callable(python_ics.SetDeviceSettings))
        self.assertTrue(callable(python_ics.SetFDBitRate))
        self.assertTrue(callable(python_ics.SetLedProperty))
        self.assertTrue(callable(python_ics.SetRTC))
        self.assertTrue(callable(python_ics.SetReflashDisplayCallback))
        self.assertTrue(callable(python_ics.SetSafeBootMode))
        self.assertTrue(callable(python_ics.SpyMessage))
        self.assertTrue(callable(python_ics.SpyMessageJ1850))
        self.assertTrue(callable(python_ics.StartDHCPServer))
        self.assertTrue(callable(python_ics.StopDHCPServer))
        self.assertTrue(callable(python_ics.TxMessages))
        self.assertTrue(callable(python_ics.UartGetBaudrate))
        self.assertTrue(callable(python_ics.UartRead))
        self.assertTrue(callable(python_ics.UartSetBaudrate))
        self.assertTrue(callable(python_ics.UartWrite))
        self.assertTrue(callable(python_ics.ValidateHObject))
        self.assertTrue(callable(python_ics.WriteJupiterFirmware))
        self.assertTrue(callable(python_ics.WriteSDCard))
        self.assertTrue(callable(python_ics.base36enc))
        self.assertTrue(callable(python_ics.close_device))
        self.assertTrue(callable(python_ics.coremini_clear))
        self.assertTrue(callable(python_ics.coremini_get_fblock_status))
        self.assertTrue(callable(python_ics.coremini_get_status))
        self.assertTrue(callable(python_ics.coremini_load))
        self.assertTrue(callable(python_ics.coremini_read_app_signal))
        self.assertTrue(callable(python_ics.coremini_read_rx_message))
        self.assertTrue(callable(python_ics.coremini_read_tx_message))
        self.assertTrue(callable(python_ics.coremini_start))
        self.assertTrue(callable(python_ics.coremini_start_fblock))
        self.assertTrue(callable(python_ics.coremini_stop))
        self.assertTrue(callable(python_ics.coremini_stop_fblock))
        self.assertTrue(callable(python_ics.coremini_write_app_signal))
        self.assertTrue(callable(python_ics.coremini_write_rx_message))
        self.assertTrue(callable(python_ics.coremini_write_tx_message))
        self.assertTrue(callable(python_ics.create_neovi_radio_message))
        self.assertTrue(callable(python_ics.disk_format))
        self.assertTrue(callable(python_ics.disk_format_cancel))
        self.assertTrue(callable(python_ics.enable_bus_voltage_monitor))
        self.assertTrue(callable(python_ics.enable_doip_line))
        self.assertTrue(callable(python_ics.enable_network_com))
        self.assertTrue(callable(python_ics.find_devices))
        self.assertTrue(callable(python_ics.firmware_update_required))
        self.assertTrue(callable(python_ics.flash_accessory_firmware))
        self.assertTrue(callable(python_ics.force_firmware_update))
        self.assertTrue(callable(python_ics.generic_api_get_status))
        self.assertTrue(callable(python_ics.generic_api_read_data))
        self.assertTrue(callable(python_ics.generic_api_send_command))
        self.assertTrue(callable(python_ics.get_accessory_firmware_version))
        self.assertTrue(callable(python_ics.get_active_vnet_channel))
        self.assertTrue(callable(python_ics.get_all_chip_versions))
        self.assertTrue(callable(python_ics.get_backup_power_enabled))
        self.assertTrue(callable(python_ics.get_backup_power_ready))
        self.assertTrue(callable(python_ics.get_bus_voltage))
        self.assertTrue(callable(python_ics.get_device_settings))
        self.assertTrue(callable(python_ics.get_device_status))
        self.assertTrue(callable(python_ics.get_disk_details))
        self.assertTrue(callable(python_ics.get_disk_format_progress))
        self.assertTrue(callable(python_ics.get_dll_firmware_info))
        self.assertTrue(callable(python_ics.get_dll_version))
        self.assertTrue(callable(python_ics.get_error_messages))
        self.assertTrue(callable(python_ics.get_gptp_status))
        self.assertTrue(callable(python_ics.get_hw_firmware_info))
        self.assertTrue(callable(python_ics.get_last_api_error))
        self.assertTrue(callable(python_ics.get_library_path))
        self.assertTrue(callable(python_ics.get_messages))
        self.assertTrue(callable(python_ics.get_pcb_serial_number))
        self.assertTrue(callable(python_ics.get_performance_parameters))
        self.assertTrue(callable(python_ics.get_rtc))
        self.assertTrue(callable(python_ics.get_script_status))
        self.assertTrue(callable(python_ics.get_serial_number))
        self.assertTrue(callable(python_ics.get_timestamp_for_msg))
        self.assertTrue(callable(python_ics.icsneoClosePort))
        self.assertTrue(callable(python_ics.icsneoEnableBusVoltageMonitor))
        self.assertTrue(callable(python_ics.icsneoEnableDOIPLine))
        self.assertTrue(callable(python_ics.icsneoEnableNetworkCom))
        self.assertTrue(callable(python_ics.icsneoFindNeoDevices))
        self.assertTrue(callable(python_ics.icsneoFirmwareUpdateRequired))
        self.assertTrue(callable(python_ics.icsneoFlashAccessoryFirmware))
        self.assertTrue(callable(python_ics.icsneoForceFirmwareUpdate))
        self.assertTrue(callable(python_ics.icsneoGenericAPIGetStatus))
        self.assertTrue(callable(python_ics.icsneoGenericAPIReadData))
        self.assertTrue(callable(python_ics.icsneoGenericAPISendCommand))
        self.assertTrue(callable(python_ics.icsneoGetAccessoryFwVersion))
        self.assertTrue(callable(python_ics.icsneoGetActiveVNETChannel))
        self.assertTrue(callable(python_ics.icsneoGetAllChipVersions))
        self.assertTrue(callable(python_ics.icsneoGetBackupPowerEnabled))
        self.assertTrue(callable(python_ics.icsneoGetBackupPowerReady))
        self.assertTrue(callable(python_ics.icsneoGetBusVoltage))
        self.assertTrue(callable(python_ics.icsneoGetDLLFirmwareInfo))
        self.assertTrue(callable(python_ics.icsneoGetDLLVersion))
        self.assertTrue(callable(python_ics.icsneoGetDeviceSettings))
        self.assertTrue(callable(python_ics.icsneoGetDeviceStatus))
        self.assertTrue(callable(python_ics.icsneoGetErrorMessages))
        self.assertTrue(callable(python_ics.icsneoGetGPTPStatus))
        self.assertTrue(callable(python_ics.icsneoGetHWFirmwareInfo))
        self.assertTrue(callable(python_ics.icsneoGetLastAPIError))
        self.assertTrue(callable(python_ics.icsneoGetMessages))
        self.assertTrue(callable(python_ics.icsneoGetPCBSerialNumber))
        self.assertTrue(callable(python_ics.icsneoGetPerformanceParameters))
        self.assertTrue(callable(python_ics.icsneoGetRTC))
        self.assertTrue(callable(python_ics.icsneoGetSerialNumber))
        self.assertTrue(callable(python_ics.icsneoGetTimeStampForMsg))
        self.assertTrue(callable(python_ics.icsneoISO15765_DisableNetworks))
        self.assertTrue(callable(python_ics.icsneoISO15765_EnableNetworks))
        self.assertTrue(callable(python_ics.icsneoISO15765_ReceiveMessage))
        self.assertTrue(callable(python_ics.icsneoISO15765_TransmitMessage))
        self.assertTrue(callable(python_ics.icsneoIsDeviceFeatureSupported))
        self.assertTrue(callable(python_ics.icsneoLoadDefaultSettings))
        self.assertTrue(callable(python_ics.icsneoOpenNeoDevice))
        self.assertTrue(callable(python_ics.icsneoReadJupiterFirmware))
        self.assertTrue(callable(python_ics.icsneoReadSDCard))
        self.assertTrue(callable(python_ics.icsneoRequestDiskDetails))
        self.assertTrue(callable(python_ics.icsneoRequestDiskFormat))
        self.assertTrue(callable(python_ics.icsneoRequestDiskFormatCancel))
        self.assertTrue(callable(python_ics.icsneoRequestDiskFormatProgress))
        self.assertTrue(callable(python_ics.icsneoRequestEnterSleepMode))
        self.assertTrue(callable(python_ics.icsneoScriptClear))
        self.assertTrue(callable(python_ics.icsneoScriptGetFBlockStatus))
        self.assertTrue(callable(python_ics.icsneoScriptGetScriptStatus))
        self.assertTrue(callable(python_ics.icsneoScriptGetScriptStatusEx))
        self.assertTrue(callable(python_ics.icsneoScriptLoad))
        self.assertTrue(callable(python_ics.icsneoScriptReadAppSignal))
        self.assertTrue(callable(python_ics.icsneoScriptReadRxMessage))
        self.assertTrue(callable(python_ics.icsneoScriptReadTxMessage))
        self.assertTrue(callable(python_ics.icsneoScriptStart))
        self.assertTrue(callable(python_ics.icsneoScriptStartFBlock))
        self.assertTrue(callable(python_ics.icsneoScriptStop))
        self.assertTrue(callable(python_ics.icsneoScriptStopFBlock))
        self.assertTrue(callable(python_ics.icsneoScriptWriteAppSignal))
        self.assertTrue(callable(python_ics.icsneoScriptWriteRxMessage))
        self.assertTrue(callable(python_ics.icsneoScriptWriteTxMessage))
        self.assertTrue(callable(python_ics.icsneoSetActiveVNETChannel))
        self.assertTrue(callable(python_ics.icsneoSetBackupPowerEnabled))
        self.assertTrue(callable(python_ics.icsneoSetBitRate))
        self.assertTrue(callable(python_ics.icsneoSetBitRateEx))
        self.assertTrue(callable(python_ics.icsneoSetContext))
        self.assertTrue(callable(python_ics.icsneoSetDeviceSettings))
        self.assertTrue(callable(python_ics.icsneoSetFDBitRate))
        self.assertTrue(callable(python_ics.icsneoSetLedProperty))
        self.assertTrue(callable(python_ics.icsneoSetRTC))
        self.assertTrue(callable(python_ics.icsneoSetReflashDisplayCallbacks))
        self.assertTrue(callable(python_ics.icsneoSetSafeBootMode))
        self.assertTrue(callable(python_ics.icsneoStartDHCPServer))
        self.assertTrue(callable(python_ics.icsneoStopDHCPServer))
        self.assertTrue(callable(python_ics.icsneoTxMessages))
        self.assertTrue(callable(python_ics.icsneoUartGetBaudrate))
        self.assertTrue(callable(python_ics.icsneoUartRead))
        self.assertTrue(callable(python_ics.icsneoUartSetBaudrate))
        self.assertTrue(callable(python_ics.icsneoUartWrite))
        self.assertTrue(callable(python_ics.icsneoValidateHObject))
        self.assertTrue(callable(python_ics.icsneoWriteJupiterFirmware))
        self.assertTrue(callable(python_ics.icsneoWriteSDCard))
        self.assertTrue(callable(python_ics.icsneowBMSManagerReset))
        self.assertTrue(callable(python_ics.icsneowBMSManagerWriteLock))
        self.assertTrue(callable(python_ics.is_device_feature_supported))
        self.assertTrue(callable(python_ics.iso15765_disable_networks))
        self.assertTrue(callable(python_ics.iso15765_enable_networks))
        self.assertTrue(callable(python_ics.iso15765_receive_message))
        self.assertTrue(callable(python_ics.iso15765_transmit_message))
        self.assertTrue(callable(python_ics.load_default_settings))
        self.assertTrue(callable(python_ics.open_device))
        self.assertTrue(callable(python_ics.override_library_name))
        self.assertTrue(callable(python_ics.read_jupiter_firmware))
        self.assertTrue(callable(python_ics.read_sdcard))
        self.assertTrue(callable(python_ics.request_enter_sleep_mode))
        self.assertTrue(callable(python_ics.set_active_vnet_channel))
        self.assertTrue(callable(python_ics.set_backup_power_enabled))
        self.assertTrue(callable(python_ics.set_bit_rate))
        self.assertTrue(callable(python_ics.set_bit_rate_ex))
        self.assertTrue(callable(python_ics.set_context))
        self.assertTrue(callable(python_ics.set_device_settings))
        self.assertTrue(callable(python_ics.set_fd_bit_rate))
        self.assertTrue(callable(python_ics.set_led_property))
        self.assertTrue(callable(python_ics.set_reflash_callback))
        self.assertTrue(callable(python_ics.set_rtc))
        self.assertTrue(callable(python_ics.set_safe_boot_mode))
        self.assertTrue(callable(python_ics.start_dhcp_server))
        self.assertTrue(callable(python_ics.stop_dhcp_server))
        self.assertTrue(callable(python_ics.transmit_messages))
        self.assertTrue(callable(python_ics.uart_get_baudrate))
        self.assertTrue(callable(python_ics.uart_read))
        self.assertTrue(callable(python_ics.uart_set_baudrate))
        self.assertTrue(callable(python_ics.uart_write))
        self.assertTrue(callable(python_ics.validate_hobject))
        self.assertTrue(callable(python_ics.wBMSManagerReset))
        self.assertTrue(callable(python_ics.wBMSManagerWriteLock))
        self.assertTrue(callable(python_ics.wbms_manager_reset))
        self.assertTrue(callable(python_ics.wbms_manager_write_lock))
        self.assertTrue(callable(python_ics.write_jupiter_firmware))
        self.assertTrue(callable(python_ics.write_sdcard))

    def test_structures_imports(self):
        self.assertIs(type(importlib.import_module('python_ics.structures', python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_extended_data_flash_header", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.neo_device", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.neo_device_ex", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.tag_options_open_neo_ex", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.tag_options_find_neo_ex", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.tagicsneo_vi_command", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.st_api_firmware_info", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.can_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.canfd_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.swcan_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.lin_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.iso9141_keyword2000_init_step", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.iso9141_keyword2000_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.uart_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.j1708_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_red_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_text_api_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.st_chip_versions", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_neo_most_gateway_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.op_eth_general_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_gptp_settings_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_gptp_and_tap_settings_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.hw_eth_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.op_eth_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ethernet_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ethernet_settings2", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ethernet10_g_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ethernet10_t1_s_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.macsec_vlantag_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.macsec_mpls_outer_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.mac_sec_rule_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.mac_sec_map_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.mac_sec_sec_y_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.mac_sec_sc_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.mac_sec_sa_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.mac_sec_flags_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.macsec_config", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.mac_sec_global_flags_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.macsec_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.logger_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.disk_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.canterm_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.timesync_icshardware_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_disk_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_disk_structure", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_disk_details", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_disk_format_progress", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.start_dhcp_server_command", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.stop_dhcp_server_command", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.extended_response_generic", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.generic_api_selector", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.generic_api_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.generic_api_data", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.generic_api_data_old", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.w_bms_manager_set_lock", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.w_bms_manager_reset", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.uart_port_data", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.uart_port_port_bytes", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.uart_port_config", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.get_supported_features_response", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.version_report", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.get_component_versions", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.get_component_versions_response", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.software_update_command", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_ext_sub_cmd_hdr", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.timestamp_", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.port_identity", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.clock_quality_", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.system_identity", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.priority_vector", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.gptp_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.generic_binary_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.serdescam_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.serdespoc_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.serdesgen_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.rad_moon_duo_converter_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.rad_reporting_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_fire_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_fire_vnet_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_cyan_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.svcan3_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.svcan4_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.svcanrf_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.secu_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pendant_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.sievb_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.seevb_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_galaxy_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_star2_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_super_moon_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.a2_b_monitor_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srada2_b_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_moon2_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_moon3_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_gigalog_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_gigastar_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_vivid_can_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.sobd2_sim_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_cm_probe_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.sobd2_pro_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.svcan412_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.secu_avb_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_l2_address_lookup_entry_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_l2_address_lookup_params_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_l2_forwarding_params_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_l2_forwarding_entry_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_l2_policing_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_vlan_lookup_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_mac_config_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_retagging_entry_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_general_params_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_vl_lookup_entry_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_vl_policing_entry_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_vl_forwarding_params_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_vl_forwarding_entry_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_avb_params_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_clock_sync_params_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_ptp_params_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_custom_params_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_pluto_switch_settings_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_pluto_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.scan_sleep_id", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.scan_hub_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_flex_vnetz_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_neo_ecu12_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.svcan4_ind_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.sobd2_lc_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_jupiter_ptp_params_s", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_jupiter_switch_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_jupiter_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.fire3_linux_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_red2_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_fire3_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_fire3_flexray_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_rad_moon_duo_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_ether_badge_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_epsilon_switch_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_epsilon_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_wil_fault_servicing_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_wil_network_data_capture_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_wil_connection_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_wil_bridge_config", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_spi_port_setting", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_spi_port_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.wbms_gateway_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.sradbms_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.srad_comet_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.global_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_device_settings", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.st_cm_iso157652_tx_message", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.iso15765_2015_tx_message", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.st_cm_iso157652_rx_message", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.spy_filter_long", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_spy_message_flex_ray", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_spy_message_mdio", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_spy_messagew_bms", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_spy_message_long", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_spy_message_vsb", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ethernet_network_status_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_fire2_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_fire2_vnet_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_vcan4_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_flex_vnetz_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_fire3_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_rad_moon_duo_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_rad_jupiter_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_obd2_pro_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_rad_pluto_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_vcan4_industrial_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_rad_epsilon_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_rad_bms_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ics_device_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_phy_reg_pkt_hdr", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_phy_reg_pkt_clause22_mess", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_phy_reg_pkt_clause45_mess", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_phy_reg_pkt", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.flash_accessory_firmware_params", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.op_eth_link_mode", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.sfp_id", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.macsec_packet_type", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.macsec_validateframe", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.macsec_strip_sectag_icv", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.macsec_cipher_suite", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.e_disk_format", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.e_disk_layout", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.extended_response_code", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.e_gptp_port", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.e_gptp_role", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.a2_btdm_mode", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.a2_b_node_type", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.flex_vnet_mode", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.epsilon_10_g_phy_select", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.e_device_settings_type", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.e_plasma_ion_vnet_channel_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ew_bms_manager_port_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ew_bms_manager_lock_state_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.e_uart_port_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.e_generic_api_options", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.ew_bms_instance_t", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_phy_reg_pkt_status", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.s_phy_reg_pkt_rw", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.device_feature", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.accessory_error_type", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.flash_accessory_index", python_ics)), ModuleType)
        self.assertIs(type(importlib.import_module("python_ics.structures.epsilon10_gphyfw", python_ics)), ModuleType)

if __name__ == "__main__":
    unittest.main()
