name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-13]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      
      - uses: mtkennerly/dunamai-action@v1
        with:
          env-var: PYTHON_ICS_VERSION
          args: from git --format "v{base}-{commit}-{timestamp}"
      - run: echo $PYTHON_ICS_VERSION

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: python_ics_wheels-${{ env.PYTHON_ICS_VERSION }}
          pattern: artifact-*
          merge-multiple: true
          path: ./wheelhouse/
