name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019] #, macOS-11]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install Clang and Clang Format
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt install clang clang-format
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install llvm
          elif [ "$RUNNER_OS" == "macoOS" ]; then
            brew install automake libtool cmake clang-format
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
          echo "Clang Version installed:"
          clang --version
          clang-format --version
          which clang
          which clang-format
        shell: bash

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.1

      - name: Build wheels
        run: |
          echo "Clang Version installed:"
          clang --version
          clang-format --version
          python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          if-no-files-found: error